/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: 'class',
    theme: {
        screens: {
            sm: '600px',
            md: '800px',
            lg: '1280px',
        },
        colors: {
            transparent: "transparent",
            black: "hsl(var(--color-black) / <alpha-value>)",
            white: "hsl(var(--color-white) / <alpha-value>)",
            primBlue: {
                50: "hsl(var(--color-primBlue-50) / <alpha-value>)",
                100: "hsl(var(--color-primBlue-100) / <alpha-value>)",
                200: "hsl(var(--color-primBlue-200) / <alpha-value>)",
                300: "hsl(var(--color-primBlue-300) / <alpha-value>)",
                400: "hsl(var(--color-primBlue-400) / <alpha-value>)",
                500: "hsl(var(--color-primBlue-500) / <alpha-value>)",
                600: "hsl(var(--color-primBlue-600) / <alpha-value>)",
                700: "hsl(var(--color-primBlue-700) / <alpha-value>)",
                800: "hsl(var(--color-primBlue-800) / <alpha-value>)",
                900: "hsl(var(--color-primBlue-900) / <alpha-value>)",
                1000: "hsl(var(--color-primBlue-1000) / <alpha-value>)",
                1050: "hsl(var(--color-primBlue-1050) / <alpha-value>)",
            },
            neutGray: {
                100: "hsl(var(--color-neutGray-100) / <alpha-value>)",
                200: "hsl(var(--color-neutGray-200) / <alpha-value>)",
                300: "hsl(var(--color-neutGray-300) / <alpha-value>)",
                400: "hsl(var(--color-neutGray-400) / <alpha-value>)",
                500: "hsl(var(--color-neutGray-500) / <alpha-value>)",
                600: "hsl(var(--color-neutGray-600) / <alpha-value>)",
                700: "hsl(var(--color-neutGray-700) / <alpha-value>)",
                800: "hsl(var(--color-neutGray-800) / <alpha-value>)",
                900: "hsl(var(--color-neutGray-900) / <alpha-value>)",
                1000: "hsl(var(--color-neutGray-1000) / <alpha-value>)",
                1050: "hsl(var(--color-neutGray-1050) / <alpha-value>)",
            },
            suppBlue: {
                100: "hsl(var(--color-suppBlue-100) / <alpha-value>)",
                200: "hsl(var(--color-suppBlue-200) / <alpha-value>)",
                300: "hsl(var(--color-suppBlue-300) / <alpha-value>)",
                400: "hsl(var(--color-suppBlue-400) / <alpha-value>)",
                500: "hsl(var(--color-suppBlue-500) / <alpha-value>)",
                600: "hsl(var(--color-suppBlue-600) / <alpha-value>)",
                700: "hsl(var(--color-suppBlue-700) / <alpha-value>)",
                800: "hsl(var(--color-suppBlue-800) / <alpha-value>)",
                900: "hsl(var(--color-suppBlue-900) / <alpha-value>)",
                1000: "hsl(var(--color-suppBlue-1000) / <alpha-value>)",
            },
            suppRed: {
                100: "hsl(var(--color-suppRed-100) / <alpha-value>)",
                200: "hsl(var(--color-suppRed-200) / <alpha-value>)",
                300: "hsl(var(--color-suppRed-300) / <alpha-value>)",
                400: "hsl(var(--color-suppRed-400) / <alpha-value>)",
                500: "hsl(var(--color-suppRed-500) / <alpha-value>)",
                600: "hsl(var(--color-suppRed-600) / <alpha-value>)",
                700: "hsl(var(--color-suppRed-700) / <alpha-value>)",
                800: "hsl(var(--color-suppRed-800) / <alpha-value>)",
                900: "hsl(var(--color-suppRed-900) / <alpha-value>)",
                1000: "hsl(var(--color-suppRed-1000) / <alpha-value>)",
            },
            suppYellow: {
                100: "hsl(var(--color-suppYellow-100) / <alpha-value>)",
                200: "hsl(var(--color-suppYellow-200) / <alpha-value>)",
                300: "hsl(var(--color-suppYellow-300) / <alpha-value>)",
                400: "hsl(var(--color-suppYellow-400) / <alpha-value>)",
                500: "hsl(var(--color-suppYellow-500) / <alpha-value>)",
                600: "hsl(var(--color-suppYellow-600) / <alpha-value>)",
                700: "hsl(var(--color-suppYellow-700) / <alpha-value>)",
                800: "hsl(var(--color-suppYellow-800) / <alpha-value>)",
                900: "hsl(var(--color-suppYellow-900) / <alpha-value>)",
                1000: "hsl(var(--color-suppYellow-1000) / <alpha-value>)",
            },
            suppGreen: {
                100: "hsl(var(--color-suppGreen-100) / <alpha-value>)",
                200: "hsl(var(--color-suppGreen-200) / <alpha-value>)",
                300: "hsl(var(--color-suppGreen-300) / <alpha-value>)",
                400: "hsl(var(--color-suppGreen-400) / <alpha-value>)",
                500: "hsl(var(--color-suppGreen-500) / <alpha-value>)",
                600: "hsl(var(--color-suppGreen-600) / <alpha-value>)",
                700: "hsl(var(--color-suppGreen-700) / <alpha-value>)",
                800: "hsl(var(--color-suppGreen-800) / <alpha-value>)",
                900: "hsl(var(--color-suppGreen-900) / <alpha-value>)",
                1000: "hsl(var(--color-suppGreen-1000) / <alpha-value>)",
            },
        },
        spacing: {
            0: '0px',
            1: '1px',
            2: '2px',
            3: '4px',
            4: '8px',
            5: '12px',
            mobileBound: '14px',
            6: '16px',
            7: '20px',
            8: '24px',
            9: '32px',
            10: '48px',
            11: '64px',
            12: '96px',
            13: '128px',
            14: '192px',
            15: '256px',
            16: '384px',
            17: '512px',
            18: '640px',
            19: '768px',
            iconMobile: '50px',
            iconSmall: '55px',
            iconMedium: '60px',
            iconLarge: '65px',
            iconButtonMobile: '36px',
            iconButtonSmall: '40px',
            iconButtonMedium: '44px',
            iconButtonLarge: '48px',
        },
        fontFamily: {
            heading: "Orbitron",
            body: "Rubik",
        },
        fontSize: {
            // fontSize, lineHeight
            0: '62.5%',
            1: ['6.4rem', '110%'],
            2: ['4.8rem', '115%'],
            3: ['3.2rem', '125%'],
            4: ['2.4rem', '135%'],
            5: ['2rem', '150%'],
            6: ['1.6rem', '175%'],
            7: ['1.4rem', '200%'],
            8: ['1.2rem', '220%'],
        },
        extend: {
            animation: {
                'hero-pointer-bounce-mobile': 'hero-pointing-mobile 1s linear infinite',
                'hero-pointer-bounce': 'hero-pointing 1s linear infinite',
            },
            keyframes: {
                'hero-pointing-mobile': {
                    '0%, 100%': { transform: 'translateY(16px)' },
                    '50%': { transform: 'translateY(0px)' },
                },
                'hero-pointing': {
                    '0%, 100%': { transform: 'rotate(45deg) translateY(16px)' },
                    '50%': { transform: 'rotate(45deg) translateY(0px)' },
                },
            },
            maxWidth: {
                read: '30em',
            },
            listStyleType: {
                none: 'none',
                square: 'square',
            },
            gridTemplateColumns: {
                timeline: 'theme(spacing.3) 1fr',
                'wide-timeline': '1fr theme(spacing.3) 1fr',
            },
            gridColumn: {
                'odd-time-item': '1',
                'mobile-time-item': '2',
                'mobile-marker-time-item': '1',
                'marker-time-item': '2',
                'even-time-item': '3',

            },
            gridRow: {
                'time-item': 'span 2',
                'mobile-time-item': '2',
                'second-time-item': '2 / 4',
                'mobile-experience-marker': '1 / span 6',
                'experience-marker': '1 / span 4',
                'education-marker': '1 / span 2',
                'mobile-education-marker': '1 / span 2',
            },
        },
    },
    safelist: [
        'ccarousel-slide-0',
        'ccarousel-slide-1',
        'ccarousel-slide-2',
        'ccarousel-slide-3',
        'ccarousel-slide-4',
        'ccarousel-slide-5',
    ],
    plugins: [],
}

